INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (1, 'Salário', 'receita');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (2, 'Investimento', 'receita');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (3, 'Aplicação', 'receita');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (4, 'Contas Residenciais', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (5, 'Educação', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (6, 'Mercado', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (7, 'Moradia', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (8, 'Saúde', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (9, 'Transporte', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (10, 'Compras', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (11, 'Bar/Restaurantes', 'despesa');
INSERT INTO public.categoria (id, nome, tipocategoria) VALUES (12, 'Cuidados Pessoais', 'despesa');