username: "hfgyisqglcifkc"
password: "e1195ff10e9e7ae7c3022130a43ee5cc78f9285b907734e2eb01b53386569190"
host: "ec2-34-233-214-228.compute-1.amazonaws.com"
port: 5432
databaseName: "d2u3vm4s445a6b"


# username: "postgres"
# password: "root"
# host: "localhost"
# port: 5432
# databaseName: "dart_week
